/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package guivideo;

/**
 *
 * @author HP
 */
import javax.swing.*;
import java.util.*;
import java.io.*;
import java.text.*;

public class EditEmployee extends javax.swing.JFrame {
    
    ArrayList<Job> jobs;
    ArrayList<Employee> employees; 
    DecimalFormat formatter;

    /**
     * Creates new form EditEmployee
     */
    public EditEmployee() {
        initComponents();
        formatter=new DecimalFormat("#,###.00");
        
         jobs=new ArrayList<Job>();
         employees=new ArrayList<Employee>();
         populateArrayList();
         
         String[] jobsArray=new String[jobs.size()];
         
         for(int i=0;i<jobs.size();i++)
         {
             jobsArray[i]=jobs.get(i).getNameOfJob()+", Rs "+ formatter.format(jobs.get(i).getSalary());
         }
         
         editJob.setModel(new javax.swing.DefaultComboBoxModel<>(jobsArray));
         
         String[] empArray=new String[employees.size()];
         
         for(int i=0;i<employees.size();i++)
         {
             empArray[i]=employees.get(i).getName()+ " "+ employees.get(i).getSurname();
         }
         
         editEmp.setModel(new javax.swing.DefaultComboBoxModel<>(empArray));
         
         editEmp.setSelectedIndex(0);
    }
    
    public void saveEmployeesToFile()
    {
        try
        {
             FileOutputStream file=new FileOutputStream("Employees.dat");
             ObjectOutputStream outputFile=new ObjectOutputStream(file);
             
             for(int i=0;i<employees.size(); i++)
             {
                 outputFile.writeObject(employees.get(i));
             }
             
             outputFile.close();
             JOptionPane.showMessageDialog(null,"Successfully saved!");
             this.dispose();
        }
        catch(IOException e)
        {
             JOptionPane.showMessageDialog(null,e.getMessage());
        }
    }
    
    public void saveEmployeesToFileDelete()
    {
        try
        {
             FileOutputStream file=new FileOutputStream("Employees.dat");
             ObjectOutputStream outputFile=new ObjectOutputStream(file);
             
             for(int i=0;i<employees.size(); i++)
             {
                 outputFile.writeObject(employees.get(i));
             }
             
             outputFile.close();
             JOptionPane.showMessageDialog(null,"Successfully deleted!");
             this.dispose();
        }
        catch(IOException e)
        {
             JOptionPane.showMessageDialog(null,e.getMessage());
        }
    }
    
    public void populateArrayList()
    {
        try
        {
            FileInputStream file=new FileInputStream("Jobs.dat");
            ObjectInputStream inputFile=new ObjectInputStream(file);
            
            boolean endOfFile=false;
            
            while(!endOfFile)
            {
                try
                {
                    jobs.add((Job) inputFile.readObject());
                }
                catch(EOFException e)
                {
                    endOfFile=true;
                }
                catch(Exception f)
                {
                    JOptionPane.showMessageDialog(null,f.getMessage());
                }
            }
            inputFile.close();
        }
        catch(IOException e )
        {
            JOptionPane.showMessageDialog(null,e.getMessage());
        }
         try
        {
            FileInputStream file2=new FileInputStream("Employees.dat");
            ObjectInputStream inputFile2=new ObjectInputStream(file2);
            
            boolean endOfFile=false;
            
            while(!endOfFile)
            {
                try
                {
                    employees.add((Employee) inputFile2.readObject());
                }
                catch(EOFException e)
                {
                    endOfFile=true;
                }
                catch(Exception f)
                {
                    JOptionPane.showMessageDialog(null,f.getMessage());
                }
            }
            inputFile2.close();
        }
        catch(IOException e )
        {
            JOptionPane.showMessageDialog(null,e.getMessage());
        }       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        editEmp = new javax.swing.JComboBox<>();
        editName = new javax.swing.JTextField();
        editSurname = new javax.swing.JTextField();
        editJob = new javax.swing.JComboBox<>();
        editNum = new javax.swing.JTextField();
        jToggleButton1 = new javax.swing.JToggleButton();
        jToggleButton2 = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Edit Employee Section");

        jLabel1.setFont(new java.awt.Font("Lucida Sans", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Edit Employee Data:");

        jLabel2.setFont(new java.awt.Font("Lucida Sans", 1, 12)); // NOI18N
        jLabel2.setText("Name:");

        jLabel3.setFont(new java.awt.Font("Lucida Sans", 1, 12)); // NOI18N
        jLabel3.setText("Surname:");

        jLabel4.setFont(new java.awt.Font("Lucida Sans", 1, 12)); // NOI18N
        jLabel4.setText("Choose emp:");

        jLabel5.setFont(new java.awt.Font("Lucida Sans", 1, 12)); // NOI18N
        jLabel5.setText("Emp job:");

        jLabel6.setFont(new java.awt.Font("Lucida Sans", 1, 12)); // NOI18N
        jLabel6.setText("Emp staff num:");

        editEmp.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        editEmp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editEmpActionPerformed(evt);
            }
        });

        editJob.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        editNum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editNumActionPerformed(evt);
            }
        });

        jToggleButton1.setFont(new java.awt.Font("Lucida Sans", 1, 10)); // NOI18N
        jToggleButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/guivideo/savefinal1.png"))); // NOI18N
        jToggleButton1.setText("Save");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });

        jToggleButton2.setFont(new java.awt.Font("Lucida Sans", 1, 10)); // NOI18N
        jToggleButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/guivideo/deletefinal.png"))); // NOI18N
        jToggleButton2.setText("Delete");
        jToggleButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(171, 171, 171)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel4)
                            .addComponent(jLabel2)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jToggleButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jToggleButton2))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(editEmp, 0, 247, Short.MAX_VALUE)
                                .addComponent(editName)
                                .addComponent(editSurname)
                                .addComponent(editJob, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(editNum)))))
                .addContainerGap(128, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel1)
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(editEmp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(editName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(editSurname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(editJob, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(editNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jToggleButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jToggleButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap(46, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        // TODO add your handling code here:
        if(editName.getText().isEmpty() || editSurname.getText().isEmpty() || editNum.getText().isEmpty())
       {
          JOptionPane.showMessageDialog(null,"Please enter all fields!"); 
       }
          else
       {
          int selectedIndex=editEmp.getSelectedIndex();
          employees.get(selectedIndex).setName(editName.getText().trim());
          employees.get(selectedIndex).setSurname(editSurname.getText().trim());
          employees.get(selectedIndex).setStaffNum(Integer.parseInt(editNum.getText()));
          Job job=jobs.get(editJob.getSelectedIndex());
          employees.get(selectedIndex).setJob(job);
          
         saveEmployeesToFile();
       }    
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    private void editEmpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editEmpActionPerformed
        int selectedIndex=editEmp.getSelectedIndex();
        
        editName.setText(employees.get(selectedIndex).getName());
        editSurname.setText(employees.get(selectedIndex).getSurname());
        editNum.setText(employees.get(selectedIndex).getStaffNum()+ "");
        
        Job job=employees.get(selectedIndex).getJob();
        int index=0;
        for(int i=0;i<jobs.size();i++)
        {
            if(jobs.get(i).equals(job))
            {
                index=i;
                break;
            }
        }
        editJob.setSelectedIndex(index);
// TODO add your handling code here:
    }//GEN-LAST:event_editEmpActionPerformed

    private void editNumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editNumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_editNumActionPerformed

    private void jToggleButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton2ActionPerformed
    int selectedIndex=editEmp.getSelectedIndex();
    
    employees.remove(selectedIndex);
    
    saveEmployeesToFileDelete();
// TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditEmployee().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> editEmp;
    private javax.swing.JComboBox<String> editJob;
    private javax.swing.JTextField editName;
    private javax.swing.JTextField editNum;
    private javax.swing.JTextField editSurname;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JToggleButton jToggleButton2;
    // End of variables declaration//GEN-END:variables
}
